"""Check bagakit-spark wording contract anchors."""

from __future__ import annotations

import argparse
from pathlib import Path


REQUIRED_PHRASES = {
    "skills/harness/bagakit-spark/README.md": [
        "co-created understanding",
        "keeps one open loop until the user explicitly completes",
        "After that action finishes, Spark must",
        "research sufficiency judgments",
        "question inventory status",
        "feedback signals from user replies",
        "MVP or thought-experiment eval envelopes",
        "rationale behind important user answers",
        "Spark owns the user-facing meaning",
        "Researcher owns source-bound evidence",
        "portable eval meaning and acceptance record",
    ],
    "skills/harness/bagakit-spark/SKILL.md": [
        "asks questions only when the answer changes a real downstream decision",
        "Spark is a conversation orchestration skill",
        "Spark must remain standalone-first",
        "Spark's normal working substrate is iterative brainstorm",
        "treats user replies as feedback signals",
        "then challenges blind spots",
        "Show the user model when it helps the goal",
        "display the user model as a status report",
        "Spark may challenge the user's stated goal",
        "Do not replace the user's goal with the agent's preference",
        "Before every response in an open spark session",
        "the response must include a next question",
        "include the confirmed key summary",
        "Asking whether to enter final confirmation",
        "counts as an end-check question",
        "current consensus snapshot candidate",
        "Do not ask another question until the current answer has changed the visible",
        "Ask no more than three questions in one turn",
        "End questioning when the user explicitly says they are",
        "publish a user-confirmed consensus snapshot",
        "accepted snapshot must include the user's acceptance record",
        "archive the previous snapshot",
        "After the user accepts a snapshot, or after the user answers the current",
        "Spark may execute that action without asking",
        "This is an execution window, not a conversation",
        "the response must include either a next",
        "or an end-check question with the current summary",
        "first substantive response must contain at least",
        "Recommended defaults may accompany the question",
        "do not replace asking it",
        "A request to \"implement\" is not by itself completion",
        "Do not create an accepted snapshot with `implicit_for_execution`",
        "only accepted after the user sees the snapshot candidate",
        "uses `bagakit-brainstorm` for durable discussion records",
        "uses `bagakit-researcher` when a branch needs evidence",
        "small MVP experiment or thought experiment",
        "discussion-level eval",
        "must trigger the consensus snapshot and user confirmation flow",
        "Spark owns the MVP eval envelope",
        "post-processing semantics",
        "other project tools may produce observations",
        "evidence packet",
        "underlying principle, criteria, alternatives considered",
        "why the principle should or should not transfer across projects",
        "plan/design stress-test submode",
        "dependent decision branches",
        "inspect local code, project documents, brainstorm state, or",
        "ask one hard branch question at a time",
        "recommended answer and rationale",
        "claims `c017` and `c018` and insight `i004`",
        "Research judgment: <research_now|research_later|research_not_needed plus rationale>",
        "Question inventory: <answered/pending/deferred/lead status for high-impact questions>",
        "Feedback signals: <positive/negative/mixed/neutral process signals when relevant>",
        "MVP eval: <hypothesis/trial/evidence packet/interpretation/snapshot impact when relevant>",
        "Eval acceptance: <accepted/corrected/rejected/incomplete plus acceptance activity when endpoint>",
        "Rationale: <principle/criteria/rejected alternative/portability boundary when relevant>",
        "Accepted snapshot: <accepted snapshot ref, candidate status, or none>",
        "eval acceptance or remaining failure signal",
        "references/question-inventory.md",
        "keep Spark's derived question inventory separate",
        "soft research gate",
        "reviewable answer to \"should we research this?\"",
        "insights, options, failure modes, and evidence-backed questions",
        "conversation-level source report",
        "does not forbid researcher-owned reports",
        "claims `c012` through `c014` and insight `i002`",
        "do not ask whether to fix the failure",
        "rerun the missed research, summary, option, or question-quality step",
        "Classify each substantive user reply as a feedback signal",
        "agreement, elaboration, trigger-for-thinking",
        "positive, negative, mixed, or neutral",
    ],
    "skills/harness/bagakit-spark/references/question-quality.md": [
        "What decision, ambiguity, or branch does this question protect?",
        "is it challenging the path or the goal itself",
        "Clarify until the agent can restate the user's goal",
        "Challenge is not contrarian performance",
        "Spark may challenge the user's goal itself",
        "Do not smuggle the agent's preference",
        "to give formative feedback about the user's knowledge",
        "Do not show the model merely because it exists",
        "Use no more than three question cards in one turn",
        "question only",
        "The loop closes when the user explicitly says they are done",
        "include the current confirmed key summary",
        "Questions that ask whether to enter final confirmation",
        "current consensus snapshot candidate in the same response",
        "first substantive response must ask at least one",
        "do not convert internal recommended defaults into silent execution",
        "not make the user's answer unnecessary",
        "It does not close the Spark loop",
        "After the action finishes, the response still needs",
        "If the question asks the user to choose among options",
        "main risk, and a recommended default",
        "Can local code, project documents, brainstorm state, or existing researcher",
        "what recommended answer should Spark offer",
        "present the inferred answer and ask only for the",
        "walk the decision tree branch by branch",
        "recommended answer, the rationale, and the risk",
        "without copying adversarial tone as a goal",
        "do not ask whether to fix it",
        "small MVP experiment or thought experiment",
        "smallest useful test",
        "Do not ask the user to reason across scattered peer artifacts",
        "extract the deeper principle",
        "portability boundary",
        "without summarizing the confirmed key points",
        "without the current consensus snapshot candidate",
        "treating accepted-snapshot execution permission as permission",
        "this question protected a real decision",
        "without explaining the research findings, rationale, risk, or recommended default",
        "asking whether to repair a question",
    ],
    "skills/harness/bagakit-spark/references/session-protocol.md": [
        "Create a branch only when it changes at least one of",
        "use brainstorm as",
        "the iterative state substrate",
        "Do not wait until the end to summarize from memory",
        "ends only when the user explicitly expresses",
        "Show it when it enables correction, shared",
        "Goal Challenge Protocol",
        "Restate the goal fairly",
        "For implementation tasks, use evidence before challenging the target",
        "Phase Labels",
        "initial_discussion",
        "in_flight_practice",
        "Feature descriptions should cite",
        "research_judgment",
        "question_inventory",
        "feedback_signals",
        "protocol-failure report",
        "converted-to-lead, not-needed",
        "references/question-inventory.md",
        "Check whether the user has explicitly completed",
        "Mandatory Question Rule",
        "first substantive response must contain a user-facing question",
        "Treat that bypass as an execution window",
        "They do not allow a final Spark response with no question",
        "Internal question inventory entries do not satisfy this rule",
        "written recommended default does not satisfy this rule",
        "Disallowed shortcuts",
        "implicit_for_execution",
        "claiming a snapshot is accepted before the user sees",
        "using an accepted snapshot as permission to end the Spark conversation",
        "must ask the user whether to end",
        "Do not ask \"should we end?\" without enough summary",
        "Asking whether to enter final confirmation",
        "is itself an end-check question",
        "current consensus snapshot candidate in the same response",
        "Research Sufficiency SOP",
        "Plan/Design Stress-Test Submode",
        "claims.md#c017",
        "claims.md#c018",
        "insights/i004.md",
        "Map the decision tree",
        "Inspect local code, project documents, brainstorm state, accepted snapshots",
        "Ask one hard dependency-bearing branch question at a time",
        "the branch being protected",
        "Spark's recommended answer",
        "risk if the recommendation is wrong",
        "soft, reviewable sensemaking gate",
        "claims.md#c012",
        "claims.md#c013",
        "claims.md#c014",
        "insights/i002.md",
        "research_now",
        "methodology design problem",
        "research_later",
        "revisited before the snapshot becomes accepted",
        "research_not_needed",
        "user preference and local anti-drift constraint",
        "decision-changing insights",
        "conversation-level source report",
        "evidence-backed question",
        "Question Repair Protocol",
        "do not ask whether to repair it",
        "rerun the missed step",
        "Evidence-Backed Question Shape",
        "Options:",
        "Recommendation:",
        "Do not ask the user to choose between labels",
        "MVP Eval Rule",
        "small MVP experiment",
        "thought experiment",
        "hypothesis",
        "evidence producer",
        "observed result",
        "interpretation",
        "failure signal",
        "process endpoint",
        "Spark owns the eval envelope",
        "Those tools are evidence producers",
        "The evidence packet should be sufficient",
        "without chasing project-local context",
        "acceptance activity in the eval envelope",
        "Rationale Ledger",
        "principle",
        "options considered",
        "portability note",
        "the deeper principle behind that reason",
        "Feedback Signal Ledger",
        "signal type",
        "valence",
        "process adjustment",
        "Do not reduce the user to a score",
        "feedback signal summary and process adjustments",
        "whether the discussion group had enough research",
        "whether the good questions and follow-up questions have been answered",
        "Consensus Snapshot",
        "The feature description should store refs",
        "research sufficiency judgment",
        "insight sufficiency judgment",
        "question inventory status",
        "Store the user's acceptance record at the end",
        "Do not store the acceptance record in a separate receipt file",
        "archive the previous snapshot",
        "Stop asking and synthesize when",
    ],
    "skills/harness/bagakit-spark/references/question-inventory.md": [
        "Spark Question Inventory",
        "without turning the conversation into a database",
        "which question it is continuing",
        "Raw user information should still be preserved",
        "| id | phase | question | source | status | decision protected | evidence refs | answer refs | follow-ups | next action |",
        "Allowed `phase` values",
        "Allowed `source` values",
        "Allowed `status` values",
        "`converted_to_research_lead`",
        "Update the inventory when",
        "validation or implementation exposes an unclear goal",
        "Before asking for convergence, closure, or snapshot acceptance",
        "Do not require every minor clarification",
        "Question Inventory Status",
        "for a later agent to reenter the right question",
    ],
    "skills/harness/bagakit-spark/references/bagakit-driver.toml": [
        "Snapshot=<accepted consensus snapshot ref or none>",
        "Research=<research_now|research_later|research_not_needed or none>",
        "Inventory=<question inventory status or none>",
        "Eval=<MVP/thought-experiment envelope ref or none>",
        "Feedback=<signal summary or none>",
        "research sufficiency judgment",
        "feedback signal summary",
    ],
    "skills/harness/bagakit-spark/references/frontdoor-rule.toml": [
        "accepted snapshot, MVP eval, or thought experiment",
        "track research sufficiency, question inventory, feedback signals, and rationale",
    ],
    "skills/harness/bagakit-spark/references/composition-boundary.md": [
        "Spark can coordinate other Bagakit skills, but it must not absorb their",
        ".bagakit/spark/",
        "Feature Provenance",
        "accepted consensus snapshot ref",
        "carry its user acceptance record at the end of the same file",
        "Routine execution updates should stay with the executing skill or agent",
        "background disciplines, prior art, best practices",
        "bring back insights, good questions, failure modes, and options",
        "Spark owns the MVP eval envelope",
        "project tools can produce concrete observations",
        "workflow stays portable across user projects",
        "evidence to justify meaning and acceptance",
        "do not leave the user-facing acceptance dependent on scattered project-local context",
        "If a peer skill is unavailable",
        "copying consensus snapshots into feature text where later updates can drift",
    ],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="repository root")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    missing: list[str] = []

    for rel_path, phrases in REQUIRED_PHRASES.items():
        path = root / rel_path
        if not path.is_file():
            missing.append(f"{rel_path}: missing file")
            continue
        text = path.read_text(encoding="utf-8")
        normalized_text = " ".join(text.split())
        for phrase in phrases:
            normalized_phrase = " ".join(phrase.split())
            if normalized_phrase not in normalized_text:
                missing.append(f"{rel_path}: missing phrase: {phrase}")

    if missing:
        print("spark contract check failed:")
        for item in missing:
            print(f"- {item}")
        return 1

    print("ok: spark wording contract anchors present")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
