set -euo pipefail

root="."

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      root="$2"
      shift 2
      ;;
    *)
      printf 'unknown argument: %s\n' "$1" >&2
      exit 2
      ;;
  esac
done

cd "$root"

cli="skills/harness/bagakit-grill/scripts/grill.sh"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

help_text="$(bash "$cli" --help)"
for command in init plan next answer attach-evidence render status; do
  if [[ "$help_text" != *"$command"* ]]; then
    printf 'missing command in help: %s\n' "$command" >&2
    exit 1
  fi
done

bash "$cli" init --root "$tmp" --run-id demo --target "Implement bagakit-grill as a compact L1 questioning skill" --target-ref "skills/harness/bagakit-grill/SKILL.md"
bash "$cli" plan --root "$tmp" --run demo --node q001 --question "Should the first implementation use a structured SSOT?" --decision "runtime state boundary" --recommended-answer "Use grill-run.json as the only run truth." --rationale "The generated brief must not become a second source of truth." --risk "Manual markdown edits would drift from the DAG."
bash "$cli" next --root "$tmp" --run demo > "$tmp/next-q001.txt"
grep -q '^next=q001$' "$tmp/next-q001.txt"
bash "$cli" answer --root "$tmp" --run demo --node q001 --answer "Yes, use grill-run.json plus a read-only brief."
bash "$cli" plan --root "$tmp" --run demo --node r001 --kind research_needed --depends-on q001 --question "Which prior art should shape the next grill question?" --decision "question quality evidence" --recommended-answer "Run bagakit-researcher through selector composition." --rationale "Grill should identify research gaps without owning research execution." --risk "The next question may copy shallow prior art."
bash "$cli" next --root "$tmp" --run demo > "$tmp/next-r001.txt"
grep -q '^next=r001$' "$tmp/next-r001.txt"
grep -q '^kind=research_needed$' "$tmp/next-r001.txt"
bash "$cli" attach-evidence --root "$tmp" --run demo --node r001 --evidence-ref ".bagakit/researcher/topics/frontier/grill/claims.md#c001" --summary "Prior art favors one question at a time with recommended answers."
bash "$cli" render --root "$tmp" --run demo
bash "$cli" status --root "$tmp" --run demo --json > "$tmp/status.json"

python3 - "$tmp" <<'PY'
import json
import pathlib
import sys

tmp = pathlib.Path(sys.argv[1])
run_path = tmp / ".bagakit" / "grill" / "runs" / "demo" / "grill-run.json"
brief_path = tmp / ".bagakit" / "grill" / "runs" / "demo" / "grill-brief.md"
surface_path = tmp / ".bagakit" / "grill" / "surface.toml"
status = json.loads((tmp / "status.json").read_text())
run = json.loads(run_path.read_text())
brief = brief_path.read_text()
surface = surface_path.read_text()

assert run["schema"] == "bagakit/grill-run/v1"
assert run["status"] == "complete"
assert len(run["question_nodes"]) == 2
assert run["question_nodes"][0]["status"] == "answered"
assert run["question_nodes"][1]["status"] == "evidence_attached"
assert len(run["qa_events"]) == 1
assert status["status"] == "complete"
assert "Generated by bagakit-grill" in brief
assert "question_nodes" not in brief
assert "qa_events" not in brief
assert 'owner_id = "bagakit-grill"' in surface
assert 'edit_policy = "generated_only"' in surface
PY

printf 'bagakit-grill smoke passed\n'
