import { type GrillNode, type GrillRun } from "./model.ts";
import { nextNode, progressCounts } from "./planner.ts";

function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function renderNext(node: GrillNode | undefined): string[] {
  if (!node) {
    return ["- Next: no ready question or research-needed node."];
  }
  const lines = [
    `- Next node: \`${node.id}\` (${node.kind}, ${node.status})`,
    `- Question: ${oneLine(node.question)}`,
  ];
  const options = node.options_considered ?? [];
  if (options.length > 0) {
    lines.push("- Options considered:");
    for (const option of options) {
      lines.push(`  - ${oneLine(option)}`);
    }
  }
  lines.push(`- Recommended answer: ${oneLine(node.recommended_answer)}`);
  if (node.risk_if_wrong) {
    lines.push(`- Risk if wrong: ${oneLine(node.risk_if_wrong)}`);
  }
  if (node.kind === "research_needed") {
    lines.push("- Action: run explicit selector/researcher composition, then attach evidence refs.");
  }
  return lines;
}

export function renderBrief(run: GrillRun): string {
  const counts = progressCounts(run);
  const next = nextNode(run);
  const lines = [
    "# Grill Brief",
    "",
    "<!-- Generated by bagakit-grill. Do not edit directly. -->",
    "",
    "## Target",
    "",
    `- Run: \`${run.run_id}\``,
    `- Status: \`${run.status}\``,
    `- Target: ${oneLine(run.target_snapshot)}`,
  ];
  if (run.target_ref) {
    lines.push(`- Target ref: \`${run.target_ref}\``);
  }
  if (run.ledger_ref) {
    lines.push(`- Consensus ledger: \`${run.ledger_ref}\``);
  }
  lines.push(
    "",
    "## Progress",
    "",
    `- total_nodes: ${run.question_nodes.length}`,
    `- ready: ${counts.ready ?? 0}`,
    `- answered: ${counts.answered ?? 0}`,
    `- research_needed: ${counts.research_needed ?? 0}`,
    `- evidence_attached: ${counts.evidence_attached ?? 0}`,
    `- convergence_check: ${run.convergence_check.status}`,
    "",
    "## Current Focus",
    "",
    ...renderNext(next),
    "",
    "## Convergence Check",
    "",
    `- Status: ${run.convergence_check.status}`,
  );
  if (run.convergence_check.goal_or_principle) {
    lines.push(`- Goal or principle: ${oneLine(run.convergence_check.goal_or_principle)}`);
  }
  if (run.convergence_check.signal) {
    lines.push(`- Signal: ${oneLine(run.convergence_check.signal)}`);
  }
  if (run.convergence_check.adjacent_branch) {
    lines.push(`- Adjacent branch: ${oneLine(run.convergence_check.adjacent_branch)}`);
  }
  if (run.convergence_check.decision) {
    lines.push(`- Decision: ${run.convergence_check.decision}`);
  }
  if (run.convergence_check.note) {
    lines.push(`- Note: ${oneLine(run.convergence_check.note)}`);
  }

  lines.push(
    "",
    "## Recent Answer",
    "",
  );

  const last = run.qa_events[run.qa_events.length - 1];
  if (last) {
    lines.push(
      `- Node: \`${last.node_id}\``,
      `- Answered at: ${last.answered_at}`,
    );
    const options = last.options_considered ?? [];
    if (options.length > 0) {
      lines.push("- Options considered:");
      for (const option of options) {
        lines.push(`  - ${oneLine(option)}`);
      }
    }
    lines.push(
      `- Raw answer: ${oneLine(last.raw_answer)}`,
    );
  } else {
    lines.push("- none");
  }

  lines.push(
    "",
    "## Source Of Truth",
    "",
    "- Authoritative run truth: `grill-run.json`",
    "- This brief is a generated summary view and intentionally omits the full DAG and QA log.",
    "",
  );

  return lines.join("\n");
}
