import { type GrillNode, type GrillRun } from "./model.ts";
import { nextNode, progressCounts } from "./planner.ts";

function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function renderNext(node: GrillNode | undefined): string[] {
  if (!node) {
    return ["- Next: no ready decision node."];
  }
  const lines = [
    `- Next node: \`${node.id}\` (${node.resolution_route}, ${node.status})`,
    `- Question: ${oneLine(node.question)}`,
  ];
  const options = node.options_considered ?? [];
  if (options.length > 0) {
    lines.push("- Options considered:");
    for (const option of options) {
      lines.push(`  - ${oneLine(option)}`);
    }
  }
  lines.push(`- Recommended resolution: ${oneLine(node.recommended_resolution)}`);
  lines.push(`- Acceptance criteria: ${oneLine(node.acceptance_criteria)}`);
  if (node.risk_if_wrong) {
    lines.push(`- Risk if wrong: ${oneLine(node.risk_if_wrong)}`);
  }
  if (node.ledger_refs.length > 0) {
    lines.push(`- Ledger refs: ${node.ledger_refs.map((ref) => `\`${ref}\``).join(", ")}`);
  }
  const actions: Record<GrillNode["resolution_route"], string> = {
    user_answer: "Ask the user one decision-bearing question and record the answer.",
    local_inspection: "Inspect local code, documents, artifacts, or tool state, then attach evidence refs.",
    external_research: "Run explicit selector/researcher composition, then attach source-bound evidence refs.",
    prototype_observation: "Produce a bounded prototype through an appropriate owner, collect observation or user-trial evidence, then attach refs.",
    runtime_experiment: "Run a bounded execution experiment, record observations, then attach evidence refs.",
  };
  if (node.resolution_route !== "user_answer") {
    lines.push(`- Action: ${actions[node.resolution_route]}`);
  }
  return lines;
}

export function renderBrief(run: GrillRun): string {
  const counts = progressCounts(run);
  const next = nextNode(run);
  const lines = [
    "# Grill Brief",
    "",
    "<!-- Generated by bagakit-grill. Do not edit directly. -->",
    "",
    "## Target",
    "",
    `- Run: \`${run.run_id}\``,
    `- Status: \`${run.status}\``,
    `- Target: ${oneLine(run.target_snapshot)}`,
  ];
  if (run.target_ref) {
    lines.push(`- Target ref: \`${run.target_ref}\``);
  }
  if (run.ledger_ref) {
    lines.push(`- Consensus ledger: \`${run.ledger_ref}\``);
  }
  lines.push(
    "",
    "## Progress",
    "",
    `- total_nodes: ${run.question_nodes.length}`,
    `- ready: ${counts.ready ?? 0}`,
    `- answered: ${counts.answered ?? 0}`,
    `- evidence_needed: ${counts.evidence_needed ?? 0}`,
    `- evidence_attached: ${counts.evidence_attached ?? 0}`,
    `- convergence_check: ${run.convergence_check.status}`,
    "",
    "## Current Focus",
    "",
    ...renderNext(next),
    "",
    "## Convergence Check",
    "",
    `- Status: ${run.convergence_check.status}`,
  );
  if (run.convergence_check.goal_or_principle) {
    lines.push(`- Goal or principle: ${oneLine(run.convergence_check.goal_or_principle)}`);
  }
  if (run.convergence_check.signal) {
    lines.push(`- Signal: ${oneLine(run.convergence_check.signal)}`);
  }
  if (run.convergence_check.adjacent_branch) {
    lines.push(`- Adjacent branch: ${oneLine(run.convergence_check.adjacent_branch)}`);
  }
  if (run.convergence_check.decision) {
    lines.push(`- Decision: ${run.convergence_check.decision}`);
  }
  if (run.convergence_check.note) {
    lines.push(`- Note: ${oneLine(run.convergence_check.note)}`);
  }

  lines.push(
    "",
    "## Recent Answer",
    "",
  );

  const last = run.qa_events[run.qa_events.length - 1];
  if (last) {
    lines.push(
      `- Node: \`${last.node_id}\``,
      `- Answered at: ${last.answered_at}`,
    );
    const options = last.options_considered ?? [];
    if (options.length > 0) {
      lines.push("- Options considered:");
      for (const option of options) {
        lines.push(`  - ${oneLine(option)}`);
      }
    }
    lines.push(
      `- Raw answer: ${oneLine(last.raw_answer)}`,
    );
  } else {
    lines.push("- none");
  }

  lines.push(
    "",
    "## Ledger Coverage",
    "",
  );
  const nodesWithLedgerRefs = run.question_nodes.filter((node) => node.ledger_refs.length > 0);
  if (nodesWithLedgerRefs.length === 0) {
    lines.push("- none");
  } else {
    for (const node of nodesWithLedgerRefs) {
      lines.push(`- \`${node.id}\`: ${node.ledger_refs.map((ref) => `\`${ref}\``).join(", ")}`);
    }
  }

  lines.push(
    "",
    "## Source Of Truth",
    "",
    "- Authoritative run truth: `grill-run.json`",
    "- This brief is a generated summary view and intentionally omits the full DAG and QA log.",
    "",
  );

  return lines.join("\n");
}
